import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import InstallBootstrap from "@/components/bootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web Avanzadas - Proyecto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="nav-fixed">
        {children}
        <InstallBootstrap></InstallBootstrap>
      </body>
    </html>
  );
}
